# Generated by Django 4.2.30 on 2026-04-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("defensa_personal", "Defensa Personal"),
                            ("jiujitsu", "Jiu-Jitsu"),
                            ("boxeo", "Boxeo"),
                            ("mma", "MMA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FighterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Adrián Gálvez", max_length=200)),
                ("nickname", models.CharField(default="The Butcher", max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("specialties", models.CharField(blank=True, max_length=500)),
                ("achievements", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("profile_image", models.ImageField(blank=True, upload_to="fighter/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Perfil del Luchador",
                "verbose_name_plural": "Perfiles",
            },
        ),
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("foto", "Foto"), ("video", "Video")], max_length=20
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="multimedia/photos/"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="URL de YouTube/Vimeo"),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, upload_to="multimedia/videos/"),
                ),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Multimedia",
                "verbose_name_plural": "Galería Multimedia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("defensa_personal", "Defensa Personal"),
                            ("jiujitsu", "Jiu-Jitsu"),
                            ("boxeo", "Boxeo"),
                            ("mma", "MMA"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=50,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("icon_class", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
                "ordering": ["order"],
            },
        ),
    ]
